Change IPCAddress to use FvmAddress
consensus-shipyard/ipc-solidity-actors pull request #133
Opened 2023-07-03 10:20 UTC by cryptoAtwill

Previously, `IPCAddress` is using `address` type. This makes sending bottom up messages from fvm to fevm impossible as fvm actors addresses are `IDActor` and fevm is using `address` type in solidity. This approach is more extendable as we are introducing more blockchains and it is aligned with FVM Address type implementation.

Changes:
- Support f4 address in `FvmAddress` struct.
- Add utility functions in `FvmAddressHelper` library to create `FVMAddress` easily and verify `FvmAddress` is indeed a valid eth delegated address.
- Update contract implementation to use `FvmAddress`
- Update tests.

2023-07-03 13:32 UTC, adlrocha requested changes
We should fix some of the tests commented and make them pass before merging. Let me know if you need help with this. 
We should also get reverted the changes to errors to use our previous approach. 
Thanks!

2023-07-03 13:32 UTC, adlrocha commented on src/lib/CrossMsgHelper.sol
> +                    from: IPCAddress({subnetId: subnet, rawAddress: FvmAddressHelper.from(BURNT_FUNDS_ACTOR)}),
Let's fix this, and set the right from instead of a `BURNT_ADDRESS`, I don't think we need tis any more.

2023-07-03 13:32 UTC, adlrocha commented on src/lib/CrossMsgHelper.sol
> +            crossMsg.message.nonce == 0 &&
Could it be that we used the hash comparison before because it is cheaper in terms of gas?

2023-07-03 13:32 UTC, adlrocha commented on src/lib/FvmAddressHelper.sol
> +    /// @notice Checks if two fil addresses are the same
Is this comment correct?

2023-07-03 13:32 UTC, adlrocha commented on src/lib/FvmAddressHelper.sol
> +        require(delegated.namespace == EAM_ACTOR, "IPC-1");
Let's revert to the convention we agreed on for errors.

2023-07-03 13:32 UTC, adlrocha commented on test/CrossMsgHelper.t.sol
> +    // TODO: comment off first, not sure what they do when address is replaced with FvmAddress
We should uncomment these tests and make them pass, let's discuss sync if needed

2023-07-03 13:32 UTC, adlrocha commented on test/CrossMsgHelper.t.sol
> +    // function test_Execute_Fails_InvalidMethod() public {
Why do we comment this one?

2023-07-03 13:32 UTC, adlrocha commented on test/FvmAddressHelper.t.sol
> +}
Should we include more tests so we have full coverage of the helper?

2023-07-03 13:32 UTC, adlrocha commented on test/Gateway.t.sol
> +    // TODO: disable for now as we are using Fvm Address
Let's uncomment this ones and fix them. They shouldn't be controversial, they may just need a few changes.

2023-07-03 13:32 UTC, adlrocha commented on test/Gateway.t.sol
> +    // TODO: disable the below for now, as we are using Fvm Address.
Same here, we should get this fixed.

2023-07-05 07:23 UTC, cryptoAtwill commented on src/lib/CrossMsgHelper.sol
> +            crossMsg.message.nonce == 0 &&
I dont think it would be cheaper than the current impl. Also we cannot use hash anymore because the EMPTY_CROSS_MSG is constant and `FvmAddress.from(address(0))` cannot be used in constant.

2023-07-05 09:01 UTC, cryptoAtwill commented on test/Gateway.t.sol
> +    // TODO: disable for now as we are using Fvm Address
as discussed we are moving these tests because FvmAddress struct is used, the address might not be a evm address only.

2023-07-05 09:12 UTC, cryptoAtwill commented on src/Gateway.sol
> +        // TODO: disable the below for now, as we are using Fvm Address.
this is removed.

2023-07-05 09:13 UTC, cryptoAtwill commented on src/lib/FvmAddressHelper.sol
> +    /// @notice Checks if two fil addresses are the same
updated

2023-07-05 09:16 UTC, cryptoAtwill commented on test/FvmAddressHelper.t.sol
> +}
removed unused functions

2023-07-05 17:48 UTC, adlrocha approved these changes

2023-07-05 17:49 UTC, merged