initial commit
consensus-shipyard/ipc-solidity-actors pull request #193
Opened 2023-08-29 00:07 UTC by cryptoAtwill

Initial attempt to store and retrieve IPC parent finality in gateway contract.

2023-08-30 07:37 UTC, dnkolegov commented on src/gateway/GatewayRouterFacet.sol
> +    function commitParentFinality(
Are we going to have `commitChildFinality` ? Why just not `commitFinality`?

2023-08-30 07:37 UTC, dnkolegov commented on src/gateway/GatewayGetterFacet.sol
> +import {CrossMsg, BottomUpCheckpoint, StorableMsg, ParentFinality} from "../structs/Checkpoint.sol";
Do we have other types of Finality besides parent?

2023-08-31 04:49 UTC, cryptoAtwill commented on src/gateway/GatewayGetterFacet.sol
> +import {CrossMsg, BottomUpCheckpoint, StorableMsg, ParentFinality} from "../structs/Checkpoint.sol";
Yep, there might be for bottom up or others in the future.

2023-08-31 04:50 UTC, cryptoAtwill commented on test/GatewayDiamond.t.sol
> +    // function testGatewayDiamond_SetMembership_Fails_ValidatorsAndWeightsNotEqual() public {
I have updated them for the commit finality, in the future, they should be removed

2023-08-31 04:50 UTC, cryptoAtwill commented on test/GatewayDiamond.t.sol
> +    // function testGatewayDiamond_SubmitTopDownCheckpoint_BigNumberOfMessages() public {
I have updated them for the commit finality, in the future, they should be removed

2023-08-31 07:37 UTC, dnkolegov commented on test/GatewayDiamond.t.sol
> +    // function testGatewayDiamond_SubmitTopDownCheckpoint_BigNumberOfMessages() public {
Could you please add this comment right into the code (in TODO) to not forget about that in the future?

2023-08-31 09:21 UTC, adlrocha requested changes
LGTM. The reason I request the change is because to wrap it up we should remove https://github.com/consensus-shipyard/ipc-solidity-actors/blob/cc109a57d62755cf849028a366258c38c04e49c8/src/gateway/GatewayManagerFacet.sol#L25. I don't think is needed anymore. If we need the `topDownGenesisEpoch` for something, we can set it directly when the first proof of finality is committed, but it can be kind of a mess having to also call this `initGenesisEpoch` implicitly when we are actually doing it implicitly when committing finality.

We can discuss sync if it is not clear.

2023-08-31 09:21 UTC, adlrocha commented on test/GatewayDiamond.t.sol
> +    // function testGatewayDiamond_SubmitTopDownCheckpoint_BigNumberOfMessages() public {
We should remove this right away. We are not going to support `submitTopDownCheckpoint` anymore, so if we want to check this code we can always look at an outdated commit.

2023-08-31 09:21 UTC, adlrocha commented on src/lib/LibGateway.sol
> +    /// @notice commit the ipc parent finality into storage
```suggestion
    /// @notice commit the ipc parent finality into storage.
    /// Committing the finality triggers the execution of top-down cross-net
    /// messages and updates the membership info.
```

2023-08-31 09:21 UTC, adlrocha commented on src/lib/LibGateway.sol
> +                s.validatorSet[s.validatorNonce][validatorAddress] = validatorWeight;
I don't think we need to address it immediately, but we will need to garbage collect the membership info instead of keeping all the history. We may be able to garbage collect outdated info.

2023-08-31 09:25 UTC, dnkolegov commented on src/lib/LibGatewayActorStorage.sol
> +    mapping(uint256 => ParentFinality) parentFinalities;
I asked about naming and @cryptoAtwill told me we have other finalities in the future like `childFinality`. If this is still true then we may need to use `parent`/`child`/`smth` prefix.

2023-08-31 09:29 UTC, adlrocha commented on src/gateway/GatewayRouterFacet.sol
> +        LibGateway.commitParentFinality(finality);
Should we do some sanity-checks here as the ones we have in Fendermint? (like that the height is over the previous height or something like that?)

2023-08-31 10:49 UTC, adlrocha commented
@cryptoAtwill, we should also remove all the code around `TopDownVoting`, `_submitTopDownVote`, etc. This is no longer necessary. I'll check the changes required to apply_messages and we can discuss if to apply them here or in some other PR.

2023-09-01 02:18 UTC, cryptoAtwill commented
@adlrocha sounds good, I will do all those deletion related work in a PR on top of this so that the changes are not mixed in this PR.

2023-09-04 07:26 UTC, cryptoAtwill commented on test/GatewayDiamond.t.sol
> +    // function testGatewayDiamond_SubmitTopDownCheckpoint_BigNumberOfMessages() public {
I removed already

2023-09-04 07:30 UTC, cryptoAtwill commented
@adlrocha I will create a separate PR to delete other methods, such as `initGenesis`. Because keep on deleting them will fail the unit tests and the PR get bigger. Another PR might be neater.

2023-09-06 03:29 UTC, cryptoAtwill commented on src/gateway/GatewayRouterFacet.sol
> +        LibGateway.commitParentFinality(finality);
yep, they are added

2023-09-06 03:31 UTC, cryptoAtwill commented on src/lib/LibGateway.sol
> +                s.validatorSet[s.validatorNonce][validatorAddress] = validatorWeight;
I added another variable to track the block height of the last committed height, we can commit and delete at the same time. I can implement this logic in follow up PRs.

2023-09-06 05:46 UTC, dnkolegov commented on src/gateway/GatewayMessengerFacet.sol
> +            revert InvalidCrossMsgValue();
@adlrocha what do you think? I think the previous error `NotEnoughFunds()` was correct

2023-09-06 09:08 UTC, cryptoAtwill commented on src/gateway/GatewayMessengerFacet.sol
> +            revert InvalidCrossMsgValue();
this is supposed to equal right?, if `msg.value` is really small, then `crossMsg.message.value` is more than required. Even though `hasFee` performs the check, but not enough fund is only valid with the `hasFee` is present. But just based on the code, it's requiring exact equal.

2023-09-11 08:04 UTC, dnkolegov approved these changes

2023-09-12 04:00 UTC, adlrocha requested changes
@cryptoAtwill, few more changes before we merge, I can address them myself if you want. Let me know.

2023-09-12 04:00 UTC, adlrocha commented on src/gateway/GatewayRouterFacet.sol
> -    function commitChildCheck(BottomUpCheckpoint calldata commit) external {
We should also keep this one in the gateway.

2023-09-12 20:13 UTC, dnkolegov commented on src/gateway/GatewayRouterFacet.sol
> +    function commitParentFinality(
Why is this method not in the GatewayActor interface?

2023-09-13 03:49 UTC, cryptoAtwill commented on src/interfaces/ISubnetActor.sol
> -    function submitCheckpoint(BottomUpCheckpoint calldata checkpoint) external;
added back

2023-09-13 03:49 UTC, cryptoAtwill commented on src/subnet/SubnetActorManagerFacet.sol
> -    function submitCheckpoint(BottomUpCheckpoint calldata checkpoint) external {
added back

2023-09-13 03:49 UTC, cryptoAtwill commented on src/gateway/GatewayRouterFacet.sol
> +    function commitParentFinality(
I added this into the interface already

2023-09-13 03:55 UTC, cryptoAtwill commented on src/gateway/GatewayRouterFacet.sol
> +    function commitParentFinality(
Right, I think this is the mechanism of the top down checkpointing in `fendermint`, not sure if it suitable to place the docs here.

But long story short, membership information is pulled from the parent `ipc-agent` or `node` in `fendermint`. Then `fendermint` call this function implicitly.

2023-09-13 04:00 UTC, cryptoAtwill commented on src/lib/LibGatewayActorStorage.sol
> +    mapping(uint256 => ParentFinality) finalitiesMap;
Not really. We just need the block height to parent finality.

2023-09-13 04:01 UTC, cryptoAtwill commented on src/gateway/GatewayRouterFacet.sol
> +    function commitParentFinality(
For top down parent finality, we dont really need mutisig.

2023-09-13 04:10 UTC, adlrocha approved these changes
Thank you for the changes, :ship:

2023-09-13 06:22 UTC, merged