Remove check
consensus-shipyard/ipc-solidity-actors pull request #266
Opened 2023-10-30 13:11 UTC by cryptoAtwill

Remove the check on `checkpointInfo.threshold` due to:
- 0 threshold is also valid threshold.
- Checkpoint info is created together with checkpoint, as long as checkpoint is created, checkpoint info will be created. Checking checkpoint should be enough.

2023-10-30 13:28 UTC, dnkolegov requested changes

2023-10-30 13:28 UTC, dnkolegov commented on src/gateway/GatewayRouterFacet.sol
> -        if (checkpointInfo.threshold == 0) {
The goal of this check was to verify that a checkpoint had been created. Before that, we suggested that the threshold cannot be equal to 0; in that case, equality to 0 meant that the checkpoint did not exist.
If the threshold can be equal to 0, then you need to implement another mechanism that allows you to verify the existence of checkpoint and checkpoint information.

2023-10-30 13:28 UTC, dnkolegov commented on src/gateway/GatewayRouterFacet.sol
> -        if (s.bottomUpCheckpointInfo[checkpoint.blockHeight].threshold > 0) {
The same comment from above is applied here.
You cannot guarantee that separate data types are managed synchronously. We need a mechanism to validate that.

You can combine those types or add a new field signaling whether checkpoint/info exists or not.

2023-10-30 13:36 UTC, cryptoAtwill commented on src/gateway/GatewayRouterFacet.sol
> -        if (s.bottomUpCheckpointInfo[checkpoint.blockHeight].threshold > 0) {
so effectively, we can create some kind of lib or wrapper to manage these two together? Because what happens now is the existence of checkpoint implies the existence of checkpoint info.

2023-10-30 13:50 UTC, dnkolegov commented on src/gateway/GatewayRouterFacet.sol
> -        if (s.bottomUpCheckpointInfo[checkpoint.blockHeight].threshold > 0) {
I do not think we need an additional library for that. 
And I do not see any problems with your last statement either.

It is enough to add a bool field in both structs and check its value instead of checking `threshold`

2023-10-30 15:51 UTC, aakoshh commented on src/gateway/GatewayRouterFacet.sol
> -        if (s.bottomUpCheckpointInfo[checkpoint.blockHeight].threshold > 0) {
It's true though that at the moment both of them are accessed together every time: inserted, read and deleted in unison. A wrapper with 2 fields (checkpoint and info) could save an extra dictionary traversal.

2023-11-01 09:00 UTC, adlrocha approved these changes
LGTM, thanks. The code looks cleaner to me know. I would let @dnkolegov, have a final pass before merging as I know he had some concerns (that being said looks fine for me).

2023-11-01 09:17 UTC, dnkolegov approved these changes

2023-11-02 03:27 UTC, merged