Federated Validation
consensus-shipyard/ipc-solidity-actors pull request #309
Opened 2023-12-08 07:36 UTC by cryptoAtwill

Adding federation validation. The approach is as follows:
- Add a `setMembership` function that takes a list of validators and their power
- Update LibStaking with `setFederatedPower` method that pushes the change to queue
- Add `confirmFederatedPower` that confirms the change
- Sort validators based on total power, power is calculated with `federatedPower + collateral`

2023-12-08 12:08 UTC, dnkolegov requested changes
- Added several minor things that should be fixed
- The main thing is I do not see any tests here despite the fact you are adding a new feature.

2023-12-08 12:08 UTC, dnkolegov commented on src/subnet/SubnetActorManagerFacet.sol
> +    modifier onlyOwner() {
Why did you copy this modifier from `LibDiamond`?

2023-12-08 12:08 UTC, dnkolegov commented on src/lib/LibStaking.sol
>      /// @notice Get the confirmed collaterals of the validators.
The description is outdated: total vs confirmed

2023-12-08 12:08 UTC, dnkolegov commented on src/subnet/SubnetActorManagerFacet.sol
> +                i++;
Is it intentional? Why not `++i`?

2023-12-08 12:08 UTC, dnkolegov commented on src/subnet/SubnetActorManagerFacet.sol
> +        for (uint i = 0; i < validators.length; ) {
Please use `for (uint256 i; i < validators.length; ) {`

2023-12-08 13:05 UTC, maciejwitowski commented
> Add a setMembership function that takes a list of validators and their power

Hm, I can't find `setMembership` in this PR. Am I missing something?

2023-12-08 13:16 UTC, maciejwitowski commented on src/lib/LibStaking.sol
> +        power = collateral + federatedPower;
One of the requirements in the design doc says
> The power of validators is not determined by their collateral in the system

Which looks inconsistent with this line (increasing `federatedPower`-based power with `collateral` ).

2023-12-11 06:16 UTC, cryptoAtwill commented on src/lib/LibStaking.sol
> +        power = collateral + federatedPower;
so the power is purely determined by `federatedPower`? Then what's the stack for?

2023-12-11 06:16 UTC, cryptoAtwill commented
@maciejwitowski It's called `setFederatedPower`.

2023-12-11 06:17 UTC, cryptoAtwill commented on src/subnet/SubnetActorManagerFacet.sol
> +    modifier onlyOwner() {
I didnt know there is a way to call modifier from a `lib`, is it possible?

2023-12-11 06:17 UTC, cryptoAtwill commented on src/subnet/SubnetActorManagerFacet.sol
> +                i++;
is there a difference? Or it's a preference?

2023-12-11 06:20 UTC, cryptoAtwill commented
@dnkolegov Please see the below:

> * Added several minor things that should be fixed

I have updated them.

> * The main thing is I do not see any tests here despite the fact you are adding a new feature.

It's an initial impl and just check in my understanding, will add them once confirmed implementation so that I dont have to change tests.

2023-12-11 06:32 UTC, dnkolegov commented on src/subnet/SubnetActorManagerFacet.sol
> +    modifier onlyOwner() {
Do we not do the same in LibReentrancyGuard?

2023-12-11 06:34 UTC, dnkolegov commented on src/subnet/SubnetActorManagerFacet.sol
> +                i++;
There is. They work differently. `++i` is cheaper. If there is no need to use `i++` we use `++i` everywhere.

2023-12-11 06:42 UTC, dnkolegov requested changes

2023-12-11 06:42 UTC, dnkolegov commented on src/subnet/SubnetActorManagerFacet.sol
> +        for (uint256 i = 0; i < validators.length; ) {
You should also delete `0` from the variable declaration. 
And store the length of the array outside of the loop.

`for (uint256 i; i < n; ) {`

2023-12-11 07:35 UTC, cryptoAtwill commented on src/subnet/SubnetActorManagerFacet.sol
> +                i++;
oh I see what you mean. Yep, I will update.

2023-12-11 10:47 UTC, maciejwitowski commented on src/lib/LibStaking.sol
> +        power = collateral + federatedPower;
My understanding is that in the latest designs, driven by the requirements from Fluence, the use of collateral mechanism is limited to specifying the min collateral when activating the subnet. This will be changed in the future but not for M3.

2023-12-11 10:48 UTC, maciejwitowski commented on src/lib/LibStaking.sol
> +        power = collateral + federatedPower;
cc @adlrocha

2023-12-11 15:22 UTC, adlrocha requested changes
I feel you ended up something more complicated than what we originally wanted. As described in my comments we want to have either a power table defined by collateral, or by power weight given by `setMembership` (what you are calling `federatedPower`). The mechanics of proposing changes and confirming should stay the same.

Ideally, we should also maybe put this permissioning into its own Facet to decouple it from the main logic and make it easy to replace.

2023-12-11 15:22 UTC, adlrocha commented on src/lib/LibStaking.sol
> +        power = collateral + federatedPower;
Correct. We should decouple the power table from the subnet lifecycle logic.
* If `permissioned` is set, we determine power through the power set by `setMembership`, we don't look at collateral. 
* If `permissioned = false` then it triggers the collateral logic that we currently have implemented.
We don't want to mix both behaviors. We should decouple this in a way that if someone wants that behavior it can easily write a facet or configure its subnet to do so (happy to sync to clarify this further).

2023-12-11 15:22 UTC, adlrocha commented on src/subnet/SubnetActorManagerFacet.sol
> +            LibStaking.setFederatedPower(validators[i], powers[i]);
We should have `federatedPower` and `collateralPower` but not both at the same time. We can probably generalize the way the collateral management works so it accepts a new `ChangeSet` that confirms collateral/power when we `setMembership`.

2023-12-12 06:35 UTC, cryptoAtwill commented on src/subnet/SubnetActorManagerFacet.sol
> +            LibStaking.setFederatedPower(validators[i], powers[i]);
that means if `permissioned == true`, we should also disable join/leave?

2023-12-12 06:39 UTC, cryptoAtwill commented on src/subnet/SubnetActorManagerFacet.sol
> +            LibStaking.setFederatedPower(validators[i], powers[i]);
my question is do we still do:
1. Order validators by their power, i.e. rank them by their power and active vs non-active?
2. Do we need validators to confirm the changes?
3. No collateral required for the federated validators?

How do we initialized fendermint from `genesis`? Will exiting scripts for generating genesis break?

2023-12-12 06:45 UTC, cryptoAtwill commented on src/subnet/SubnetActorManagerFacet.sol
> +            LibStaking.setFederatedPower(validators[i], powers[i]);
If we dont do this, then we will break the entire `fendermint` validator update flow or at least requires some major changes.

2023-12-13 12:39 UTC, adlrocha reviewed
This is looking better. A few suggestions before we approve and merge:
* Let's remove the `permissioned` flag and just use `permissionMode` to determine the permissioning logic used, it will help abstracting this in the future. 
* As I've mentioned a few times, I am not a fan of having `federatedPower` and `collateralPower` as two different fields, I feel we should just have `power` and decouple the permissioning logic so it decides how to interpret the power and how it should be updated. I understand that making this change may require some refactoring and it would take more time, but it would help if we want to fully abstract this in the future. In any case, this should work, so I will let @maciejwitowski have the final call on this, considering the time constraints :)  (also, Maciej, related to our huddle, this is a good example of the trade-offs between doing the right thing or moving fast that we've been having).

2023-12-13 12:39 UTC, adlrocha commented on test/integration/SubnetActorDiamond.t.sol
> +    // function _assertJoin(address validator, uint256 amount) internal {
Why are we commenting this tests? If this is because there is no easy way to deploy a gateway with other parameters we should parametrize the test setup so we can cover all possible tests and different situations.

2023-12-13 12:39 UTC, adlrocha commented on src/subnet/SubnetActorManagerFacet.sol
> +    function setFederatedPowers(
I am honestly not a fan of this name for the function, we could maybe call it `setMembershipConfig` which is the more "academic" name for what we are doing? 
```suggestion
    function setFederatedPower(
```

2023-12-13 12:39 UTC, adlrocha commented on src/structs/Subnet.sol
> +enum PermissionMode {
I think it would be cleaner if you remove the `permissioned` flag and add here a `Static` permission mode to flag where no changes to the validator set is allowed.

2023-12-13 12:39 UTC, adlrocha commented on src/subnet/SubnetActorManagerFacet.sol
> +        if (!s.permissioned) {
As described in a comment above, ideally we should check the permission mode here to determine if the method is allowed or not.

2023-12-13 12:39 UTC, adlrocha commented on src/SubnetActorDiamond.sol
> +        if (params.permissioned) {
I think it may be good to pass the `permissionedMode` here instead of using a flag, maybe?

2023-12-13 12:39 UTC, adlrocha commented on src/lib/LibStaking.sol
> +        uint256[] memory activePowers = new uint256[](size);
Instead of using `Powers` should we maybe use `PowerTable` throughout the code? I think way is clearer what we mean.   
```suggestion
        uint256[] memory activePowerTable = new uint256[](size);
```

2023-12-13 12:39 UTC, adlrocha commented on src/structs/Subnet.sol
> +    uint256 federatedPower;
I understand that it is simpler this way, but as we discussed sync I am not a fan of having `federatedPower` and `collateralPower` as to distinct entities. Ideally `ValidatorInfo` should just have a `power` field and according to the `PermissionMode` the specific logic is triggered. I feel this would allow us in the future to abstract and modularize the permissioning system.  But I guess that with the time we have left it may be good enough :shrug:

2023-12-13 12:52 UTC, cryptoAtwill commented on src/structs/Subnet.sol
> +    uint256 federatedPower;
Yeah, but if we change to power, a lot of the parameters and their meanings need to be updated as well. Like in the release queue, we are allowing validators to withdraw their collateral, which makes total sense. But if we change to power and interpret as collateral, it's withdrawing power, which I feel will be misleading.

2023-12-13 12:55 UTC, cryptoAtwill commented on test/integration/SubnetActorDiamond.t.sol
> +    // function _assertJoin(address validator, uint256 amount) internal {
It should be removed in dev, but when I rebase, it leaked into my PR. I will remove them.

2023-12-13 12:57 UTC, cryptoAtwill commented on src/SubnetActorDiamond.sol
> +        if (params.permissioned) {
It would break existing `fendermint` and `ipc` code base, or do we code freeze there as well?

2023-12-13 12:59 UTC, maciejwitowski commented
IIUC we are in the situation where we can either go into Solidity audits with the current implementation (+ fixing all PR comments ofc) or none. I agree we should refactor but I doubt we'd land it by tomorrow. 
In this case, I think we should stick with the current implementation + adding more tests.

2023-12-13 14:45 UTC, adlrocha commented
Wait, why has this PR been closed? Fixing all my comments except https://github.com/consensus-shipyard/ipc-solidity-actors/pull/309#discussion_r1425292767 (that we chose to defer), should make it good to go?

2023-12-13 14:58 UTC, cryptoAtwill commented
@adlrocha I closed it temporarily because it keeps on triggering the CI which creates a lot of rebase and uses unnecessary resources. I tried marking it as draft, but still runs.

2023-12-13 15:05 UTC, cryptoAtwill commented on src/subnet/SubnetActorManagerFacet.sol
> +        if (!s.permissioned) {
I have updated them all.

2023-12-13 15:05 UTC, cryptoAtwill commented on src/structs/Subnet.sol
> +enum PermissionMode {
That flag is removed in storage, but I kept it in the contructor params as this way it wont break existing `fendermint` and `ipc` codebase.

2023-12-14 10:44 UTC, maciejwitowski commented on binding/src/lib_gateway.rs
> +<<<<<<< HEAD
There are bunch of unaddressed merge conflicts. Not sure what the plan is as I see this is active topic in the Slack thread.

2023-12-14 10:48 UTC, maciejwitowski commented on src/SubnetActorDiamond.sol
> +        if (params.permissioned) {
We don't code freeze `fendermint` and `ipc` yet (today). IIUC we could use the `permissionedMode` and adapt other repos, right?

2023-12-14 11:03 UTC, maciejwitowski reviewed
I guess @adlrocha may want to take another look but I did a pass since the time is limited today.

2 things
- The only unaddressed comment is about [function name change](https://github.com/consensus-shipyard/ipc-solidity-actors/pull/309/files#r1425273419). It's a small thing but let's address for completeness 
- There are not fixed merge commits in rust bindings. These have to be fixed (depending on the slack convo outcome)

Other than that LGTM.

2023-12-14 14:21 UTC, maciejwitowski approved these changes

2023-12-14 14:48 UTC, adlrocha commented on src/structs/Subnet.sol
> +    Federated
We are missing a `Static` mode for when we want to disable joining validators after bootstrapping the subnet

2023-12-14 14:48 UTC, adlrocha commented on src/subnet/SubnetActorManagerFacet.sol
> +        if (s.bootstrapped) {
We should  not remove the `s.permissioned` but making it `PermissionMode.Static`, if not this is a huge bug and we won't allow joining anyone once a subnet is bootstrapped.

2023-12-14 14:48 UTC, adlrocha commented on src/subnet/SubnetActorManagerFacet.sol
> -        if (s.permissioned) {
Same here, we should disable staking if `Static` or `Federated` is enabled.

2023-12-14 14:48 UTC, adlrocha commented on src/subnet/SubnetActorManagerFacet.sol
> -        if (s.permissioned) {
Same here

2023-12-14 14:48 UTC, adlrocha commented on src/subnet/SubnetActorManagerFacet.sol
> -        if (s.bootstrapped && s.permissioned) {
And here

2023-12-14 14:58 UTC, cryptoAtwill commented on src/subnet/SubnetActorManagerFacet.sol
> -        if (s.permissioned) {
that means we should `enforceCollateralValidation` right? The implementation does that?

2023-12-14 14:58 UTC, cryptoAtwill commented on src/subnet/SubnetActorManagerFacet.sol
> +        if (s.bootstrapped) {
The current implementation still allows join after bootstrap, there is a test case covering it.

2023-12-14 15:14 UTC, adlrocha approved these changes
OK, funny story, Github was showing an outdated version of the code and my comments do not apply. Thank you @cryptoAtwill for syncing, we wouldn't have realized.

2023-12-14 15:26 UTC, dnkolegov approved these changes

2023-12-14 15:55 UTC, merged