Pausable
consensus-shipyard/ipc-solidity-actors pull request #323
Opened 2023-12-12 07:36 UTC by cryptoAtwill

Add `pausable` to subnet actor such that operations with `whenNotPaused` will be blocked when necessary.

2023-12-12 10:37 UTC, dnkolegov requested changes
I suggest using https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/Pausable.sol as a reference: use functions names and semantics.

2023-12-12 10:37 UTC, dnkolegov commented on src/lib/LibPausable.sol
> +    function isPausabled() external view returns(bool) {
I think it should be named `isPaused`

2023-12-12 10:37 UTC, dnkolegov commented on src/lib/LibPausable.sol
> +    function isPausabled() external view returns(bool) {
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/Pausable.sol

2023-12-12 10:37 UTC, dnkolegov commented on src/lib/LibPausable.sol
> +    function setPausable(bool paused) internal {
Why do you need an argument? Why do we need setPausable(false)?
It should be named like `pause()`.
I suggest using functions names and semantics from https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/Pausable.sol

2023-12-12 10:37 UTC, dnkolegov commented on src/subnet/SubnetActorManagerFacet.sol
> +    function leave() external whenNotPaused nonReentrant notKilled {
`nonreentrant` always should be first one

2023-12-12 10:37 UTC, dnkolegov commented on src/subnet/SubnetActorManagerFacet.sol
> +    function claim() external whenNotPaused nonReentrant {
nonreentrant always should be the first one

2023-12-12 10:37 UTC, dnkolegov commented on src/subnet/SubnetActorManagerFacet.sol
> +    function claimRewardForRelayer() external whenNotPaused nonReentrant {
nonreentrant always should be the first one

2023-12-12 10:43 UTC, dnkolegov commented
> Add `pausable` to subnet actor such that operations with `whenNotPaused` will be blocked when necessary.

Are we going to add pausability for Gateways?

2023-12-13 15:44 UTC, cryptoAtwill commented
close temporarily to avoid generating `out` and `binding`.

2023-12-13 16:00 UTC, cryptoAtwill commented
@dnkolegov I have updated the code based on your feedbacks. Please take another look.

2023-12-13 16:02 UTC, dnkolegov approved these changes

2023-12-14 19:55 UTC, merged