GatewayRouterFacet diamond split up to fix contract size errors
consensus-shipyard/ipc-solidity-actors pull request #408
Opened 2023-12-20 03:20 UTC by snissn

Based on the discussion in this issue https://github.com/consensus-shipyard/ipc-monorepo/issues/9 I have begun to split the GatewayRouterFacet into four files. The files currently compile and more work needs to be done on fixing all of the tests and the deployment scripts

2023-12-20 09:11 UTC, dnkolegov commented on src/gateway/router/CrossMessageApplicationFacet.sol
> +contract CrossMessageApplicationFacet is GatewayActorModifiers {
I don't know if this name reflects what this facet implements.
For me, it sounds like we have a cross-message application, and the facet is about this application.
Should we call it CrossChainMessageHandlerFacet or just CrossChainMessageFacet ?

2023-12-20 09:13 UTC, dnkolegov commented on src/gateway/router/MessageBatchManagementFacet.sol
> +    function _applyMessages(SubnetID memory arrivingFrom, CrossMsg[] memory crossMsgs) internal {
I think this is a duplicate of the function from CrossChainApplicationFacet

2023-12-20 09:13 UTC, dnkolegov commented on src/gateway/router/MessageBatchManagementFacet.sol
> +    function _applyMsg(SubnetID memory arrivingFrom, CrossMsg memory crossMsg) internal {
This one is also duplicate

2023-12-20 15:02 UTC, raulk requested changes

2023-12-20 15:02 UTC, raulk commented on scripts/deploy-gateway.template.ts
> +            name: 'CheckpointManagementFacet',
```suggestion
            name: 'CheckpointingFacet',
```

2023-12-20 15:02 UTC, raulk commented on scripts/deploy-gateway.template.ts
>          { name: 'GatewayManagerFacet', libs: managerFacetLibs },
Since we're doing this, I think we should break this one into four facets:

| Facet | Methods |
|--------|--------|
| SubnetLifecycleFacet | register, kill |
| CollateralFacet | addStake, releaseStake |
| SupplyFacet | fund, fundWithToken, release | 
| RewardFacet | releaseRewardForRelayer | 

Can do in a follow-up PR.

2023-12-20 15:02 UTC, raulk commented on scripts/deploy-gateway.template.ts
>          { name: 'GatewayMessengerFacet', libs: messengerFacetLibs },
Let's drop the `Gateway` prefix from facets? It's a bit verbose as the namespace is already implied by the import path? Can do in a follow-up PR.

2023-12-20 15:02 UTC, raulk commented on scripts/deploy-gateway.template.ts
> +            name: 'CrossMessageApplicationFacet',
```suggestion
            name: 'TopDownRouterFacet',
```

2023-12-20 15:02 UTC, raulk commented on scripts/deploy-gateway.template.ts
> +        { name: 'FinalityManagementFacet', libs: finalityManagementFacetLibs },
```suggestion
        { name: 'TopDownFinalityFacet', libs: finalityManagementFacetLibs },
```

2023-12-20 15:02 UTC, raulk commented on scripts/deploy-gateway.template.ts
> +            name: 'MessageBatchManagementFacet',
```suggestion
            name: 'BottomUpRouterFacet',
```

2023-12-20 15:03 UTC, raulk commented
(Agree with @dnkolegov's input on naming choices and his pointing out that some methods are duplicated; I think we'll need to extract those to a lib?)

2023-12-20 17:12 UTC, snissn commented on scripts/deploy-gateway.template.ts
>          { name: 'GatewayMessengerFacet', libs: messengerFacetLibs },
this is so funny because as I was rounding out the end of the work I did yesterday on this PR I realized "OH NO I DIDN"T INCLUDE GATEWAY IN THE NAME" and expected that was the direction the feedback will land on this PR! :)

2023-12-21 00:15 UTC, raulk approved these changes
Just a couple of naming adjustments, and we'd be good to go. Approving in anticipation, but let's get the renames in pls.

2023-12-21 00:15 UTC, raulk commented on scripts/deploy-gateway.template.ts
> +        { name: 'FinalityFacet', libs: finalityFacetLibs },
@dnkolegov Let's call this `TopDownFinalityFacet` to avoid confusion, as this doesn't track any finality, only the parent's finality on a child subnet.

2023-12-21 00:15 UTC, raulk commented on scripts/deploy-gateway.template.ts
> +    const crossMessagingFacetLibs: Libraries = {
@dnkolegov we are starting to call this "xnet messaging", so let's name this facet `XnetMessagingFacet`?

2023-12-21 02:12 UTC, snissn commented on src/gateway/router/CrossMessageApplicationFacet.sol
> +contract CrossMessageApplicationFacet is GatewayActorModifiers {
```
 src/gateway/router/{MessageBatchManagementFacet.sol => BottomUpRouterFacet.sol} |  83 ++---------------------------------------
 src/gateway/router/{CheckpointManagementFacet.sol => CheckpointingFacet.sol}    |   2 +-
 src/gateway/router/CrossMessageApplicationFacet.sol                             |  99 ------------------------------------------------
 src/gateway/router/CrossMessagingFacet.sol                                      |  35 +++++++++++++++++
 src/gateway/router/{FinalityManagementFacet.sol => FinalityFacet.sol}           |   2 +-
```

2023-12-21 02:27 UTC, snissn commented on scripts/deploy-gateway.template.ts
> +        { name: 'FinalityFacet', libs: finalityFacetLibs },
@dnkolegov I took care of this!. This commit renames the FinalityFacet to the TopDownFinalityFacet pushed code for this here: 3d1b398c

2023-12-21 02:34 UTC, snissn commented on scripts/deploy-gateway.template.ts
> +    const crossMessagingFacetLibs: Libraries = {
@dnkolegov Please confirm if this looks good to you, I made this change here 8b2b7f27 to rename CrossMessaging to XnetMessaging

2023-12-21 06:34 UTC, dnkolegov commented on scripts/deploy-gateway.template.ts
> +            name: 'CrossMessageApplicationFacet',
TopDown is not good since the facet contains logic related to top-down and bottom-up. What about CrossMessagingFacet?

2023-12-21 06:34 UTC, dnkolegov commented on scripts/deploy-gateway.template.ts
>          { name: 'GatewayManagerFacet', libs: managerFacetLibs },
I would break into the following: subnet lifecycle related, checkpoint messaging related, and supply + reward related ()

register, kill, addStake, releaseStake, unstake should live together because they implement the same protocol

2023-12-21 06:34 UTC, dnkolegov commented on scripts/deploy-gateway.template.ts
> +    const crossMessagingFacetLibs: Libraries = {
LGTM

2023-12-21 06:34 UTC, dnkolegov commented on scripts/deploy-gateway.template.ts
> +        { name: 'FinalityFacet', libs: finalityFacetLibs },
LGTM

2023-12-21 06:47 UTC, dnkolegov approved these changes

2023-12-21 06:48 UTC, merged

2023-12-21 07:03 UTC, snissn commented
🎉