Full validators
consensus-shipyard/ipc-solidity-actors pull request #97
Opened 2023-06-20 09:32 UTC by cryptoAtwill

List the details of validators.

2023-06-20 09:43 UTC, adlrocha approved these changes
LGTM. Let's maybe call it `ValidatorInfo` instead of `ValidatorDetails` if you don't mind.

2023-06-20 09:43 UTC, adlrocha commented on src/SubnetActor.sol
> +    struct ValidatorDetail {
```suggestion
    struct ValidatorInfo {
```

2023-06-20 09:43 UTC, adlrocha commented on src/SubnetActor.sol
> +    function getValidators() public view returns (address[] memory) {
Why changing `external` to `public`?

2023-06-20 09:46 UTC, cryptoAtwill commented on src/SubnetActor.sol
> +    function getValidators() public view returns (address[] memory) {
it's called in the `getValidatorsInfo`.

2023-06-20 09:49 UTC, cryptoAtwill commented on src/SubnetActor.sol
> +    struct ValidatorDetail {
updated

2023-06-20 09:50 UTC, cryptoAtwill commented on src/SubnetActor.sol
> +    function getValidators() public view returns (address[] memory) {
I changed back to external

2023-06-20 10:27 UTC, adlrocha requested changes
We should increase the config number also when the stake of a validator that is already part of the subnet changes. And the sequence number only increases, even when a validator leaves.

2023-06-20 10:27 UTC, adlrocha commented on src/SubnetActor.sol
> +                configurationNumber += 1;
The configuration number should also be increased when the stake for an existing validator is increased, as this changes their weight.

2023-06-20 10:27 UTC, adlrocha commented on src/SubnetActor.sol
> +    uint64 public configurationNumber;
It would be cleaner to include the configuration number in a struct aggregating all validator information, but I guess for now this is good enough.

2023-06-20 10:28 UTC, adlrocha commented on src/SubnetActor.sol
> +        configurationNumber -= 1;
Why are you reducing the configuration number here? The configuration number only increases, both when a validator joins and when it leaves.

2023-06-20 10:28 UTC, cryptoAtwill commented on src/SubnetActor.sol
> +    uint64 public configurationNumber;
I created that struct, we can migrate to use that struct later

2023-06-20 10:28 UTC, cryptoAtwill commented on src/SubnetActor.sol
> +        configurationNumber -= 1;
typo, should be plus

2023-06-20 10:32 UTC, cryptoAtwill commented on src/SubnetActor.sol
> +        configurationNumber -= 1;
updated

2023-06-20 10:32 UTC, adlrocha approved these changes
LGTM now!

2023-06-29 14:11 UTC, adlrocha approved these changes

2023-06-29 14:11 UTC, merged